import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Home from "./components/Home";
import Skill from "./components/Skill";
import ThreeBackground from "./components/ThreeBackground";
import Project from "./components/Project";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0F1629]`}>

        <ThreeBackground />
        <Navigation />
        <section>
          <Home />
        </section>

        <section>
          <Skill />
        </section>
        <section>
          <Project />
        </section>
        {children}
      </body>
    </html>
  );
}